apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: duplicati
spec:
  provider: vault
  secretObjects:
  - secretName: duplicati
    type: Opaque
    data: 
    - objectName: ARGS
      key: ARGS
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: duplicati
    objects: |
      - objectName: "ARGS"
        secretPath: "apps-kv/data/duplicati/config"
        secretKey: "ARGS"
