apiVersion: v1
kind: Service
metadata:
  name: duplicati
spec:
  selector:
    app: duplicati
    part-of: duplicati
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: duplicati
---
kind: Service
apiVersion: v1
metadata:
  name: ak-outpost-proxy01
spec:
  type: ExternalName
  externalName: ak-outpost-proxy01.authentik.svc.cluster.local
  ports:
  - port: 9000
    targetPort: 9000
