---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: duplicati
  annotations:
    nfs.io/storage-path: "data01/duplicati"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sources
  annotations:
    nfs.io/storage-path: "data01/"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
